name: Update 3D contribution graph

on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:
  push:
    branches: [main]
    paths: [".github/workflows/profile.yml"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit 3D graph
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile-3d-contrib
          git commit -m "chore: update 3D contribution graph" || exit 0
          git push
